[build.environment]
  NPM_FLAGS = "--version"
  NODE_VERSION = "16"

[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/gallery"
  to = "https://gallery.ekar.site"
  force = true